TRAINING_DATA = [

    # greeting
    ("hello", "greeting"),
    ("hi there", "greeting"),
    ("good morning", "greeting"),
    ("hey", "greeting"),
    ("hi", "greeting"),
    ("good afternoon", "greeting"),
    ("good evening", "greeting"),
    ("hello there", "greeting"),
    ("hey there", "greeting"),
    ("greetings", "greeting"),
    ("howdy", "greeting"),
    ("hi assistant", "greeting"),
    ("hello assistant", "greeting"),
    ("good day", "greeting"),
    ("hey assistant", "greeting"),

    # check_balance
    ("what is my balance", "check_balance"),
    ("show balance", "check_balance"),
    ("how much money do i have", "check_balance"),
    ("check my balance", "check_balance"),
    ("how much is in my account", "check_balance"),
    ("tell me my balance", "check_balance"),
    ("account balance", "check_balance"),
    ("what is my account balance", "check_balance"),
    ("show me my balance", "check_balance"),
    ("how much do i have", "check_balance"),
    ("current balance", "check_balance"),
    ("check account balance", "check_balance"),
    ("how much money is in my account", "check_balance"),
    ("balance please", "check_balance"),
    ("what is my current balance", "check_balance"),
    ("show my account balance", "check_balance"),

    # transfer_money
    ("transfer money", "transfer_money"),
    ("send 200 pounds", "transfer_money"),
    ("make a transfer", "transfer_money"),
    ("i want to send money", "transfer_money"),
    ("transfer 500 pounds", "transfer_money"),
    ("send funds", "transfer_money"),
    ("pay someone", "transfer_money"),
    ("send 100 pounds", "transfer_money"),
    ("i want to transfer money", "transfer_money"),
    ("make a payment", "transfer_money"),
    ("send money to someone", "transfer_money"),
    ("transfer 1000 pounds", "transfer_money"),
    ("i need to send money", "transfer_money"),
    ("wire transfer", "transfer_money"),
    ("move money", "transfer_money"),
    ("send payment", "transfer_money"),

    # recent_transactions
    ("show recent transactions", "recent_transactions"),
    ("transaction history", "recent_transactions"),
    ("my last transactions", "recent_transactions"),
    ("what did i spend", "recent_transactions"),
    ("show my payments", "recent_transactions"),
    ("show transaction history", "recent_transactions"),
    ("last transactions", "recent_transactions"),
    ("recent payments", "recent_transactions"),
    ("what are my recent transactions", "recent_transactions"),
    ("show me my transactions", "recent_transactions"),
    ("my spending history", "recent_transactions"),
    ("list my transactions", "recent_transactions"),
    ("what transactions did i make", "recent_transactions"),
    ("show last payments", "recent_transactions"),
    ("my payment history", "recent_transactions"),

    # advisory_loan
    ("i want a mortgage", "advisory_loan"),
    ("home loan options", "advisory_loan"),
    ("tell me about loans", "advisory_loan"),
    ("i need a loan", "advisory_loan"),
    ("can i get a loan", "advisory_loan"),
    ("advise me on loans", "advisory_loan"),
    ("i want to apply for a loan", "advisory_loan"),
    ("loan advice", "advisory_loan"),
    ("what loan should i take", "advisory_loan"),
    ("help me choose a loan", "advisory_loan"),
    ("recommend a loan", "advisory_loan"),
    ("which loan is best for me", "advisory_loan"),
    ("i want financial advice on loans", "advisory_loan"),
    ("mortgage advice", "advisory_loan"),
    ("best loan for me", "advisory_loan"),

    # loan_info
    ("loan information", "loan_info"),
    ("what loans do you offer", "loan_info"),
    ("personal loan", "loan_info"),
    ("auto loan", "loan_info"),
    ("loan interest rate", "loan_info"),
    ("what is the loan rate", "loan_info"),
    ("loan conditions", "loan_info"),
    ("tell me about your loans", "loan_info"),
    ("loan products", "loan_info"),
    ("what types of loans are available", "loan_info"),
    ("loan requirements", "loan_info"),
    ("how to apply for a loan", "loan_info"),
    ("loan terms", "loan_info"),
    ("car loan", "loan_info"),
    ("business loan", "loan_info"),
    ("student loan", "loan_info"),

    # deposit_info
    ("open deposit", "deposit_info"),
    ("deposit options", "deposit_info"),
    ("savings account", "deposit_info"),
    ("fixed term deposit", "deposit_info"),
    ("interest rate on deposit", "deposit_info"),
    ("what deposits do you offer", "deposit_info"),
    ("i want to open a deposit", "deposit_info"),
    ("deposit interest rate", "deposit_info"),
    ("how much interest on deposit", "deposit_info"),
    ("tell me about deposits", "deposit_info"),
    ("savings options", "deposit_info"),
    ("i want to save money", "deposit_info"),
    ("deposit account", "deposit_info"),
    ("fixed deposit", "deposit_info"),
    ("how to open a savings account", "deposit_info"),
    ("best deposit rate", "deposit_info"),

    # card_info
    ("i want a card", "card_info"),
    ("credit card options", "card_info"),
    ("debit card", "card_info"),
    ("cashback card", "card_info"),
    ("what cards do you offer", "card_info"),
    ("i need a credit card", "card_info"),
    ("tell me about your cards", "card_info"),
    ("card with cashback", "card_info"),
    ("travel card", "card_info"),
    ("i want to apply for a card", "card_info"),
    ("credit card interest rate", "card_info"),
    ("credit limit", "card_info"),
    ("card benefits", "card_info"),
    ("best credit card", "card_info"),
    ("how to get a debit card", "card_info"),
    ("virtual card", "card_info"),

    # investment_info
    ("i want to invest", "investment_info"),
    ("investment options", "investment_info"),
    ("mutual funds", "investment_info"),
    ("how to invest my money", "investment_info"),
    ("investment products", "investment_info"),
    ("where to invest", "investment_info"),
    ("stocks and bonds", "investment_info"),
    ("i want to grow my money", "investment_info"),
    ("portfolio management", "investment_info"),
    ("what investment options do you have", "investment_info"),
    ("government bonds", "investment_info"),
    ("investment returns", "investment_info"),
    ("how to start investing", "investment_info"),
    ("managed portfolio", "investment_info"),
    ("investment advice", "investment_info"),

    # insurance_info
    ("i need insurance", "insurance_info"),
    ("life insurance", "insurance_info"),
    ("property insurance", "insurance_info"),
    ("health insurance", "insurance_info"),
    ("what insurance do you offer", "insurance_info"),
    ("insurance products", "insurance_info"),
    ("i want to buy insurance", "insurance_info"),
    ("insurance rates", "insurance_info"),
    ("home insurance", "insurance_info"),
    ("car insurance", "insurance_info"),
    ("tell me about insurance", "insurance_info"),
    ("insurance coverage", "insurance_info"),
    ("travel insurance", "insurance_info"),
    ("insurance policy", "insurance_info"),
    ("how much is insurance", "insurance_info"),

    # internet_banking
    ("how to use internet banking", "internet_banking"),
    ("mobile app", "internet_banking"),
    ("online banking", "internet_banking"),
    ("how to login", "internet_banking"),
    ("banking app", "internet_banking"),
    ("how to use mobile banking", "internet_banking"),
    ("i cannot login", "internet_banking"),
    ("forgot password", "internet_banking"),
    ("how to register for online banking", "internet_banking"),
    ("mobile banking features", "internet_banking"),
    ("how to use the app", "internet_banking"),
    ("online account access", "internet_banking"),
    ("digital banking", "internet_banking"),
    ("how to pay online", "internet_banking"),
    ("internet banking help", "internet_banking"),

    # confirm_otp
    ("123456", "confirm_otp"),
    ("my code is 123456", "confirm_otp"),
    ("confirm code", "confirm_otp"),
    ("otp code", "confirm_otp"),
    ("verification code", "confirm_otp"),
    ("my otp is 123456", "confirm_otp"),
    ("enter code", "confirm_otp"),
    ("code 123456", "confirm_otp"),
    ("confirm 123456", "confirm_otp"),
    ("my verification code is 123456", "confirm_otp"),
    ("submit code", "confirm_otp"),
    ("one time password", "confirm_otp"),
    ("confirm my code", "confirm_otp"),
    ("the code is 123456", "confirm_otp"),
    ("use code 123456", "confirm_otp"),
]